# ASSIGNMENT 3

In [1]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [5]:
import numpy as np
list1=[]
list2=[]
print("list1")
for i in range (0, 5):
    item=int(input())
    list1.append(item)
print ("List2")
for i in range (0, 5):
    c=int(input())
    list2.append(c)
arr1 = np.array(list1)
arr2 = np.array(list2)
arr3 = np.concatenate((list1, list2))
print (np.sort(arr3))

list1
3
5
6
2
23
List2
34
65
87
1
4
[ 1  2  3  4  5  6 23 34 65 87]


In [6]:
ndarry = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("No. of dimensions: ", ndarry.ndim)
 
print("Shape of array: ", ndarry.shape)
 
print("Size of array: ", ndarry.size)

No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6


Question 4 How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet


In [15]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
a2=a[np.newaxis, :]
print(a2.ndim)
print(a2.shape)
b = np.expand_dims(a, axis=1)
print(b.shape)

2
(1, 7)
(7, 1)


Question 5 Consider two square numpy arrays. Stack them vertically and horizontally.

In [16]:
a = np.array([[1, 22], 
              [3, 4]]) 
  
b = np.array([[15, 36], 
              [17, 28]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b))) 
  

Vertical stacking:
 [[ 1 22]
 [ 3  4]
 [15 36]
 [17 28]]

Horizontal stacking:
 [[ 1 22 15 36]
 [ 3  4 17 28]]


Question 6 How to get unique items and counts of unique items?

In [6]:
import numpy as np
a = [2,3,4,5,5,8,9,1,4,3]
print (np.unique(a))
print ("Return the count of repetitions of unique elements:") 
u,indices = np.unique(a,return_counts = True) 
print (u) 
print (indices)

[1 2 3 4 5 8 9]
Return the count of repetitions of unique elements:
[1 2 3 4 5 8 9]
[1 1 2 2 2 1 1]
